
package com.ttdev.bs;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */
//import javax.ws.rs.client.Client;
//import javax.ws.rs.client.ClientBuilder;
//import javax.ws.rs.core.Response;
import com.sun.jersey.api.client.Client;
import com.sun.jersey.api.client.WebResource;
import com.sun.jersey.core.util.MultivaluedMapImpl;

//import antlr.Token;

import com.sun.jersey.api.client.ClientResponse;
//import org.apache.cxf.jaxrs.client.WebClient;

import javax.ws.rs.client.Entity;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.MultivaluedMap;

//import java.net.MalformedURLException;
//import java.net.URL;
import org.apache.cxf.jaxrs.ext.form.Form;
//import javax.xml.namespace.QName;
//import javax.xml.ws.Service;
//import org.apache.cxf.rs.security.oauth.data.Token;
import org.apache.commons.lang.StringUtils;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2018-04-17T12:48:03.802-01:00
 * Generated source version: 2.7.18
 * 
 */
public final class SimpleService_P1_Client {

    private static final QName SERVICE_NAME = new QName("http://ttdev.com/ss", "SimpleService");

    private SimpleService_P1_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
    	
    	Client client2 = Client.create();
		
		WebResource webResource = client2.resource("http://pccompshop.com/home/?q=es/endpoint/comment/4");
		ClientResponse response = webResource.accept("application/xml").get(ClientResponse.class);
		Result result = response.getEntity(Result.class);
		System.out.println(result.getSubject());
		
		
		WebResource webResource2P = client2.resource("http://pccompshop.com/home/?q=es/endpoint/user/token");
		ClientResponse response2P = webResource2P.type(MediaType.APPLICATION_FORM_URLENCODED_TYPE).post(ClientResponse.class, null);
		String outputP = response2P.getEntity(String.class);
		String token = StringUtils.substringBetween(outputP, "<token>", "</token>");
		System.out.println("Token: "+token);
		
		
		
		MultivaluedMap params = new MultivaluedMapImpl();
		params.add("username", "test");
		params.add("password", "test");
		WebResource webLogin = client2.resource("http://pccompshop.com/home/?q=es/endpoint/user/login");
		ClientResponse responseLogin = webLogin.header(token, "X-CSRF-Token").type(MediaType.APPLICATION_FORM_URLENCODED).post(ClientResponse.class, params);
		String output = responseLogin.getEntity(String.class);
		System.out.println(output);
		
		String newToken = StringUtils.substringBetween(output, "<token>", "</token>");
		System.out.println("New Token: "+newToken);
		String SessionId = StringUtils.substringBetween(output, "<sessid>", "</sessid>");
		System.out.println("Session ID: "+SessionId);
		String SessionName = StringUtils.substringBetween(output, "<session_name>", "</session_name>");
		System.out.println("Session name: "+SessionName);
		
		//result.setSubject("COMENTARIO NUEVO");
		System.out.println("Nuevo título: "+result.getSubject());
		//Result.CommentBody comment = result.getCommentBody();
		//System.out.println("Comentario: "+comment);
		
		
		
   
    	
    	
        URL wsdlURL = SimpleService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SimpleService_Service ss = new SimpleService_Service(wsdlURL, SERVICE_NAME);
        SimpleService port = ss.getP1();  
        
        {
        System.out.println("Invoking concat...");
        java.lang.String _concat_s1 = result.getSubject();
        java.lang.String _concat_s2 = "PEPITO";
        java.lang.String _concat__return = port.concat(_concat_s1, _concat_s2);
        System.out.println("concat.result=" + _concat__return);
        result.setSubject(_concat__return);
        WebResource change = client2.resource("http://pccompshop.com/home/?q=es/endpoint/comment/4");
		ClientResponse respuesta = change.header(newToken, "X-CSRF-Token").header("cookie",SessionName+"="+SessionId).put(ClientResponse.class, result);
		String prf = respuesta.getEntity(String.class);
		System.out.println(prf);


        }

        System.exit(0);
    }

}
